DROP TABLE IF EXISTS Categories;
DROP TABLE IF EXISTS Qualifiers;
DROP TABLE IF EXISTS Authors;
DROP TABLE IF EXISTS Refs;
DROP TABLE IF EXISTS Claims;
DROP TABLE IF EXISTS Users;
DROP TABLE IF EXISTS Statements;
DROP TABLE IF EXISTS Events;